# %% [markdown]
# # Q7 — does the serving stack change the answer, or only the number? (secondary)
#
# The paper's headline numbers come from six models served **locally** (vLLM /
# `transformers`, on-premises GPUs). The same six models are also available
# through OpenRouter's `:free` tier, an API-served stack, on the `base` image
# variant only. This notebook is not a search for the more accurate pathway —
# it is not one, in any way that survives being stated plainly. It asks a
# narrower and more useful question: **can the API number be regenerated by
# anyone who did not run it themselves?**
#
# **The argument in one paragraph, so the tables below are read the right way
# round.** The two serving pathways return different values on about half of
# 27,720 matched responses. Overall MAE improves through the API for three of
# the six models, so this is not a story about one pathway being worse. What
# makes the local pathway the one this study reports is that it is
# **specified**: framework, precision and hardware are recorded, and
# re-running the protocol reproduced 100 of 100 responses exactly for five of
# six models. OpenRouter's `:free` tier discloses neither the quantization,
# the model revision nor the decoding parameters behind a given call, and any
# of them may change between requests without notice. A number produced
# through the API cannot be regenerated, because the system that produced it
# is not specified — a researcher calling the same endpoint next year is not
# running the same experiment and has no way to tell whether they are. **This
# is a claim about reproducibility, not about accuracy, and the tables below
# are read that way throughout: a smaller API overall MAE is not a point in
# the API's favour, it is one more number nobody else can reproduce.**
#
# **What this comparison can and cannot conclude.** Local memory footprints
# recorded during the local runs are consistent with bf16 weights at each
# model's parameter count, so the local side sits on a known footing. The API
# side does not: nothing in this repository establishes what precision,
# quantization or model revision OpenRouter served. Any disagreement between
# the two pathways below is therefore never attributed to the serving stack
# alone — it could be the stack, the weights, or both, and no test here can
# separate them. Every claim in this notebook is worded "stack and possibly
# weights", and a close agreement is read the same way in reverse: evidence
# the two *behave* similarly, never evidence they run identical weights.
#
# Two further constraints bind everything below. **No API latency claim of
# any kind** — the API run hit rate limits and retried, so its latency
# measures rate-limiting and retry timing, not inference speed, and is not
# analysed here. **API confidence is not compared to local confidence**, and
# no API confidence claim is made for Llama-4-Maverick, whose API confidence
# value is 42% exactly 1.0. **No campaign-clustered companion is computed
# anywhere in this notebook** — the three campaigns are diverse by design and
# cannot support a dependable cluster-robust interval with only three clusters.

# %% [markdown]
# ## Setup
#
# The seed is fixed so every resample below is reproducible.
#
# **RNG discipline.** Every bootstrap quantity below draws from its own
# generator, seeded from `SEED` plus a fixed integer offset recorded next to
# its declaration: isolating each quantity's draws means adding or removing
# one bootstrap elsewhere in this notebook cannot silently move a number
# already read from another part. **Point estimates are deterministic
# functions of the loaded data and are asserted against fixed published
# values** — this cell fails if any of them moves, so a change to the
# analysis cannot silently invalidate the manuscript. Interval endpoints are
# not asserted against a fixed value, because a bootstrap interval's exact
# endpoints depend on the draw sequence and are expected to vary slightly
# from run to run; the assertions below check the interval excludes or
# includes zero where the reported conclusion depends on that, not its exact
# bounds.

# %%
import os
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats


def _locate_project_root(start=None):
    """Resolve the project root independently of the kernel's cwd. See
    `Q1_accuracy.py` for the full rationale — this cell does not need
    `_common` imported yet to locate it.
    """
    p = Path(os.environ.get("ANALYSIS_PROJECT_ROOT", start or Path.cwd())).resolve()
    for candidate in [p, *p.parents]:
        if (candidate / "STATUS.md").is_file():
            return candidate
    raise RuntimeError(f"project root not found from {p}")


sys.path.insert(0, str(_locate_project_root() / "03_notebooks_definitive"))
import pathlib as _pl  # `_common.py` is imported from this notebook's
sys.path.insert(0, str(_pl.Path(__file__).resolve().parent))  # own directory
import _common as co

SEED = 20260914

# Offsets declared here and nowhere else:
#   +0  per-configuration and per-model MAE_o / MAE_b level CIs (both paths)
#   +1  paired local-minus-API difference CIs (MAE_o and MAE_b), per configuration and per model
#   +2  Maverick determinism floor (delta_Mav CI, over the 100-image subsample)
#   +3  rank-reversal pairs: local-path MAE_b difference CI, one draw per flipped pair
rng_level_ci = np.random.default_rng(SEED + 0)
rng_diff_ci = np.random.default_rng(SEED + 1)
rng_maverick = np.random.default_rng(SEED + 2)
rng_reversal = np.random.default_rng(SEED + 3)

ROOT = co.project_root()
RESULTS_DIR = ROOT / "05_deliverables/Repository/GitHub/results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
RENDERED_DIR = ROOT / "05_deliverables/Repository/GitHub/notebooks" / "rendered"
RENDERED_DIR.mkdir(parents=True, exist_ok=True)

pd.set_option("display.width", 160)
pd.set_option("display.max_columns", 30)


def assert_reproduces(name: str, computed: float, published: float, atol: float = 1e-3) -> None:
    """Published values. This cell fails if any of them moves, so a change to
    the analysis cannot silently invalidate the manuscript. `atol=1e-3`
    because the published values are stated to three decimal places, not at
    full float precision.
    """
    if not np.isclose(computed, published, atol=atol, rtol=0):
        raise AssertionError(
            f"{name}: computed {computed!r} does not match the published value "
            f"{published!r} (atol={atol})"
        )


# %% [markdown]
# ## Data
#
# The local-path frame is the same `variant == 'base'`, local-stack frame
# every other question in this project shares (1,155 images x 6 models x 4
# prompts = 27,720 rows). The API frame has no variant column at all — the API
# was only ever run on the `base` images — so it is built the same way by
# hand and joined to the same authoritative reference every other question
# uses, so the two pathways are compared on frames constructed identically in
# every respect but the serving path. The load-time checks below run first
# and stop the notebook if the input files are not the ones this analysis was
# built on; pairing completeness (every image has exactly 24 base/local rows)
# and the count of exactly-reproduced determinism-check images are checked
# explicitly, since the shared load routine does not check them on its own.

# %%
checks_df, frames = co.run_all_assertions(include_d12=False)
print(checks_df[["id", "description", "passed"]].to_string(index=False))
assert checks_df["passed"].all(), "one or more load-time assertions failed -- stopping"

d1 = frames["d1"]
d5 = frames["d5"]
base_local = frames["base_local"]

k1_result = co.assert_k1_pairing_complete(d5, base_local)
print(f"K1 ({k1_result.id}): {k1_result.description} -> passed={k1_result.passed}; {k1_result.detail}")

# %%
d6 = co.load_d6()


def build_base_api_frame(d6: pd.DataFrame, d1: pd.DataFrame) -> pd.DataFrame:
    """The API analysis frame: base variant (implicit), all 6 models, built
    identically to the local-path frame (same reference, same bin
    convention) so the two pathways are compared on frames that differ only
    in the serving stack, never in how they were constructed.
    """
    df = d6.merge(
        d1[["image", "reference", "campaign"]],
        on="image", how="inner", validate="many_to_one",
    )
    if len(df) != len(d6):
        raise AssertionError(f"D6 -> D1 join dropped rows: {len(d6)} in, {len(df)} out")
    df["e"] = df["vegetation_percent"] - df["reference"]
    df["abs_e"] = df["e"].abs()
    df["bin"] = co.assign_bins(df["reference"])
    return df


base_api = build_base_api_frame(d6, d1)
print(f"local base frame: {len(base_local)} rows; API base frame: {len(base_api)} rows")

api_counts = base_api.groupby("model").agg(n_rows=("image", "size"), n_images=("image", "nunique"))
assert (api_counts["n_rows"] == 4620).all() and (api_counts["n_images"] == 1155).all(), (
    f"unexpected API frame shape:\n{api_counts}"
)
print("Design is fully matched: 1,155 images x 4 prompts x 6 models = 27,720 responses on each "
      "path, and every model has all 4,620 of its API predictions -- no missing API predictions.")

# %% [markdown]
# Llama-4-Maverick was the one model that did not reproduce every response
# exactly when the local protocol was re-run on a 100-image subsample at
# temperature 0 — 92 of 100 matched exactly, and every one of the 8
# disagreements was exactly 10 cover points. That run-to-run gap is a floor on
# what any claim about Maverick can attribute to the serving stack: an
# observed difference smaller than the model's own run-to-run noise is not
# distinguishable from that noise. It is computed once here, on the
# overall-MAE scale, from the same 100-image subsample every other question
# in this project uses, and carried into every Maverick row below.

# %%
d8 = co.load_d8()
maverick_floor = co.compute_maverick_floor(d8, rng_maverick)
c11_result = co.assert_c11_n_reproduced(maverick_floor.n_reproduced)
print(f"C11 ({c11_result.id}): passed={c11_result.passed}; {c11_result.detail}")
print(
    f"delta_Mav (overall-MAE scale) = {maverick_floor.delta_mav:.4f} cover points "
    f"(95% BCa CI [{maverick_floor.delta_mav_ci_lo:.4f}, {maverick_floor.delta_mav_ci_hi:.4f}])"
)
assert_reproduces("delta_Mav", maverick_floor.delta_mav, 0.65, atol=0.01)
assert_reproduces("delta_Mav_ci_lo", maverick_floor.delta_mav_ci_lo, 0.25, atol=0.05)
assert_reproduces("delta_Mav_ci_hi", maverick_floor.delta_mav_ci_hi, 1.15, atol=0.05)
print("Determinism floor matches the published value: 0.65 [0.25, 1.15] cover points.")

# %% [markdown]
# ## Assumption checks
#
# **Pairing is complete**, checked above from the shared load-time checks:
# every image has exactly 24 base/local rows.
#
# **Tie burden.** A heavy tie burden — many images where the two pathways
# land on exactly the same value — makes a rank test's tie-correction do most
# of the work, so it is reported alongside every Wilcoxon row rather than
# left implicit. Checked here per model, on the per-image mean-absolute-error
# local-minus-API difference the Wilcoxon below is computed from.
#
# **Normality of the paired stack difference** is reported for context: no
# method in this notebook assumes it, which is why the empirical 2.5/97.5
# percentile limits of agreement are reported below rather than Bland-Altman's
# conventional ±1.96 SD limits.
#
# **Between-image independence** is assumed and not checkable from this data.
# No cluster-robust companion is computed to measure the cost of that
# assumption — three campaigns are too few to support a dependable
# cluster-robust interval.

# %%
k3_rows = []
diffs_by_model = {}
for model in co.MODELS:
    loc_img = base_local[base_local["model"] == model].groupby("image")["abs_e"].mean()
    api_img = base_api[base_api["model"] == model].groupby("image")["abs_e"].mean()
    diff = (loc_img - api_img).reindex(loc_img.index).values
    diffs_by_model[model] = diff
    k3 = co.check_k3_tie_burden(diff)
    k3_rows.append({"model": model, **k3})

k3_df = pd.DataFrame(k3_rows)
print("Tie burden of the per-image local-minus-API absolute-error difference, by model:")
print(k3_df.to_string(index=False))

# %%
k5_rows = []
for model in co.MODELS:
    loc = base_local[base_local["model"] == model]
    api = base_api[base_api["model"] == model]
    merged = loc.merge(api, on=["image", "prompt"], suffixes=("_local", "_api"), validate="one_to_one")
    stack_diff = (merged["vegetation_percent_local"] - merged["vegetation_percent_api"]).values
    k5 = co.check_k5_normality(stack_diff)
    k5_rows.append({"model": model, **k5, "normality_rejected": k5["p_value"] < 0.05})

k5_df = pd.DataFrame(k5_rows)
print("\nD'Agostino-Pearson normality of the pooled stack difference, by model (context only):")
print(k5_df.to_string(index=False))

# %% [markdown]
# ## Analysis
#
# **Why the API path gets the same treatment the local path gets.** Agreement
# quantities alone -- exact-agreement rate, median absolute difference,
# limits of agreement, rank correlation -- do not touch the reference and
# cannot say whether a model is *more accurate* through one path than the
# other. Computing overall MAE, balanced MAE, their bootstrap
# intervals and a paired Wilcoxon on the API side, exactly as Q1 computes them
# on the local side, is not done so the API numbers can be reported as a
# result -- it is done so the comparison between the two paths is a fair one,
# built from the same statistics on both sides.
#
# **Overall MAE and balanced MAE are read the same way here as everywhere
# else in this study.** Overall MAE carries the one test -- the paired
# two-sided Wilcoxon signed-rank on per-image absolute error -- corrected
# with Holm-Bonferroni across the six models (first threshold 0.05/6 =
# 0.00833). Balanced MAE is never compared by a p-value: its local-minus-API
# difference is a BCa interval, uncorrected, read one at a time. The 24 model
# x prompt configuration rows carry neither correction: they are descriptive,
# with intervals.

# %%
FAMILY_SIZE_Q7 = 6
HOLM_ALPHA = 0.05
holm_threshold_q7 = co.holm_first_threshold(HOLM_ALPHA, FAMILY_SIZE_Q7)
print(f"Holm-Bonferroni across the six per-model Wilcoxon tests, first threshold = "
      f"{HOLM_ALPHA}/{FAMILY_SIZE_Q7} = {holm_threshold_q7:.5f}.")


def level_metrics(frame: pd.DataFrame, group_cols: list) -> dict:
    """Overall MAE and balanced MAE for one (model[, prompt]) group on one
    pathway, pooling per-image mean absolute error over any axis not in
    `group_cols` -- the per-image value is the mean of the absolute error,
    never the absolute error of the mean prediction, so pooling never
    behaves like an ensemble.
    """
    out = {}
    for keys, g in frame.groupby(group_cols):
        keys = keys if isinstance(keys, tuple) else (keys,)
        per_image = g.groupby("image").agg(abs_e=("abs_e", "mean"), bin=("bin", "first"))
        bal = co.balanced_mae(per_image["abs_e"], per_image["bin"])
        out[keys] = {
            "overall_mae": float(per_image["abs_e"].mean()),
            "balanced_mae": bal.balanced_mae,
            "per_image": per_image,
        }
    return out


local_by_combo = level_metrics(base_local, ["model", "prompt"])
api_by_combo = level_metrics(base_api, ["model", "prompt"])
local_by_model = level_metrics(base_local, ["model"])
api_by_model = level_metrics(base_api, ["model"])

print(f"Configurations (24): local computed for {len(local_by_combo)}, API for {len(api_by_combo)}")
print(f"Models (6): local computed for {len(local_by_model)}, API for {len(api_by_model)}")

# %% [markdown]
# **A performance note that changes no statistic.** This notebook needs many
# more image bootstraps than most -- four level intervals and two difference
# intervals per configuration, the same six per model, plus one per reversed
# pair -- and the shared bootstrap routine's per-replicate statistic rebuilds
# a `pandas` frame and regroups it on every one of tens of thousands of
# resamples, which is correct but needlessly slow at this call volume. The
# functions below replace only the *inside* of that statistic -- reducing a
# bin-mean or a balanced-MAE evaluation to plain array lookups on a resample
# that the same resampling and pairing logic still produces. Every number
# this produces is checked against the shared, slower implementation once
# below, so the speed-up is verified to compute the identical quantity, not
# merely a faster-looking one.

# %%
_BIN_CODE_MAP = {label: i for i, label in enumerate(co.BIN_LABELS)}


def _fast_overall_mean(abs_e: np.ndarray) -> float:
    return float(abs_e.mean())


def _fast_balanced_mae(abs_e: np.ndarray, bin_codes: np.ndarray) -> float:
    """Numerically identical to the shared balanced-MAE function -- the
    unweighted mean of the five per-bin means -- computed with `np.add.at`
    instead of a `groupby`, so the same quantity is reached without rebuilding
    a `pandas` frame on every bootstrap replicate.
    """
    sums = np.zeros(5)
    counts = np.zeros(5)
    np.add.at(sums, bin_codes, abs_e)
    np.add.at(counts, bin_codes, 1)
    with np.errstate(invalid="ignore"):
        per_bin = sums / counts
    return float(np.nanmean(per_bin))


def make_per_image_arrays(per_image: pd.DataFrame) -> dict:
    """Precompute the numpy arrays a fast statistic needs from a per-image
    frame (index = image, columns abs_e/bin), once per configuration/model
    rather than once per bootstrap replicate.
    """
    frame = per_image.reset_index()
    return {
        "image": frame["image"].values,
        "abs_e": frame["abs_e"].values,
        "bin_code": frame["bin"].map(_BIN_CODE_MAP).values,
    }


def fast_image_bootstrap(per_image: pd.DataFrame, stat: str, rng: np.random.Generator,
                          B: int = co.B_BOOTSTRAP) -> "co.BootstrapResult":
    """The image bootstrap -- resample images with replacement, recompute the
    statistic on each resample, take a BCa interval with a fallback to the
    plain percentile interval where BCa's bias-correction or acceleration is
    undefined -- with the same draw sequence and the same fallback rule as
    the shared implementation, but evaluating `stat` from precomputed numpy
    arrays instead of rebuilding a `pandas` frame and regrouping it on every
    replicate. `stat` is `'overall_mae'` or `'balanced_mae'`, evaluated on
    one pathway's own per-image frame.
    """
    arrays = make_per_image_arrays(per_image)
    images_all = arrays["image"]
    abs_e_all = arrays["abs_e"]
    bin_all = arrays["bin_code"]
    pos_by_image = {img: i for i, img in enumerate(images_all)}
    n = len(images_all)

    def statistic_on_positions(positions: np.ndarray) -> float:
        a = abs_e_all[positions]
        if stat == "overall_mae":
            return _fast_overall_mean(a)
        return _fast_balanced_mae(a, bin_all[positions])

    theta_hat = statistic_on_positions(np.arange(n))

    boot_vals = np.empty(B)
    n_violations = 0
    idx_array = np.arange(n)
    for i in range(B):
        drawn = rng.choice(idx_array, size=n, replace=True)
        present_bins = set(bin_all[drawn])
        if len(present_bins) < 5:
            n_violations += 1
        boot_vals[i] = statistic_on_positions(drawn)

    jack_vals = np.empty(n)
    full_mask = np.ones(n, dtype=bool)
    for i in range(n):
        full_mask[i] = False
        jack_vals[i] = statistic_on_positions(idx_array[full_mask])
        full_mask[i] = True

    lo = np.percentile(boot_vals, 2.5)
    hi = np.percentile(boot_vals, 97.5)
    ci_method = "percentile (BCa fallback)"
    bca_lo, bca_hi, used_bca = co._bca_interval(theta_hat, boot_vals, jack_vals, alpha=0.05)
    if used_bca:
        lo, hi, ci_method = bca_lo, bca_hi, "BCa"

    return co.BootstrapResult(
        estimate=theta_hat, ci_lo=lo, ci_hi=hi, ci_method=ci_method,
        boot_values=boot_vals, n_empty_bin_violations=n_violations, p_two_sided=None,
    )


def fast_paired_diff_bootstrap(per_image_local: pd.DataFrame, per_image_api: pd.DataFrame,
                                stat: str, rng: np.random.Generator,
                                B: int = co.B_BOOTSTRAP) -> "co.BootstrapResult":
    """The local-minus-API difference of one metric, bootstrapped by
    resampling images once per replicate and evaluating both sides on the
    same drawn image set, so a resample never scores one path on one set of
    images and the other path on a different set. Verified against the
    shared, slower implementation below.
    """
    merged = per_image_local.reset_index().merge(
        per_image_api.reset_index(), on="image", suffixes=("_local", "_api"),
    )
    images_all = merged["image"].values
    abs_e_local = merged["abs_e_local"].values
    abs_e_api = merged["abs_e_api"].values
    bin_local = merged["bin_local"].map(_BIN_CODE_MAP).values
    bin_api = merged["bin_api"].map(_BIN_CODE_MAP).values
    n = len(images_all)

    def statistic_on_positions(positions: np.ndarray) -> float:
        if stat == "overall_mae":
            return _fast_overall_mean(abs_e_local[positions]) - _fast_overall_mean(abs_e_api[positions])
        bal_l = _fast_balanced_mae(abs_e_local[positions], bin_local[positions])
        bal_a = _fast_balanced_mae(abs_e_api[positions], bin_api[positions])
        return bal_l - bal_a

    theta_hat = statistic_on_positions(np.arange(n))
    idx_array = np.arange(n)

    boot_vals = np.empty(B)
    n_violations = 0
    for i in range(B):
        drawn = rng.choice(idx_array, size=n, replace=True)
        present_bins = set(bin_local[drawn])
        if len(present_bins) < 5:
            n_violations += 1
        boot_vals[i] = statistic_on_positions(drawn)

    jack_vals = np.empty(n)
    full_mask = np.ones(n, dtype=bool)
    for i in range(n):
        full_mask[i] = False
        jack_vals[i] = statistic_on_positions(idx_array[full_mask])
        full_mask[i] = True

    lo = np.percentile(boot_vals, 2.5)
    hi = np.percentile(boot_vals, 97.5)
    ci_method = "percentile (BCa fallback)"
    bca_lo, bca_hi, used_bca = co._bca_interval(theta_hat, boot_vals, jack_vals, alpha=0.05)
    if used_bca:
        lo, hi, ci_method = bca_lo, bca_hi, "BCa"

    return co.BootstrapResult(
        estimate=theta_hat, ci_lo=lo, ci_hi=hi, ci_method=ci_method,
        boot_values=boot_vals, n_empty_bin_violations=n_violations, p_two_sided=None,
    )


# %% [markdown]
# **Verifying the fast path against the shared, slower one.** One
# configuration (the observed-best local configuration) is bootstrapped both
# ways with the same seed, and the point estimates -- which are deterministic
# and must match exactly -- and the interval endpoints -- which must match to
# floating-point tolerance, since both draw from `rng.choice` in the same
# sequence -- are compared before the fast path is trusted for the full table.

# %%
_verify_pi = local_by_combo[("Llama-4-Maverick", "Short")]["per_image"]
_rng_a = np.random.default_rng(999_001)
_rng_b = np.random.default_rng(999_001)
_slow = co.image_bootstrap(
    _verify_pi.reset_index(), lambda f: co.balanced_mae(f["abs_e"], f["bin"]).balanced_mae,
    _rng_a, image_col="image", bin_col="bin", B=2_000,
)
_fast = fast_image_bootstrap(_verify_pi, "balanced_mae", _rng_b, B=2_000)
assert np.isclose(_slow.estimate, _fast.estimate, atol=1e-9), "fast-path point estimate diverged from the shared implementation"
assert np.isclose(_slow.ci_lo, _fast.ci_lo, atol=1e-6) and np.isclose(_slow.ci_hi, _fast.ci_hi, atol=1e-6), (
    "fast-path interval diverged from the shared implementation under an identical draw sequence"
)
print(f"Fast-path verification passed: balanced MAE = {_fast.estimate:.4f} "
      f"[{_fast.ci_lo:.4f}, {_fast.ci_hi:.4f}] on both implementations (B=2,000 check run).")

# The paired-difference fast path is checked the same way, on the same
# configuration against its API counterpart, so the difference statistic --
# not only the single-pathway statistic above -- is confirmed identical to
# the shared implementation before it is trusted for every configuration,
# model and reversal-pair row below.
_verify_pi_api = api_by_combo[("Llama-4-Maverick", "Short")]["per_image"]
_rng_c = np.random.default_rng(999_002)
_rng_d = np.random.default_rng(999_002)


def _slow_diff_stat(f):
    bal_l = co.balanced_mae(f["abs_e_local"], f["bin_local"]).balanced_mae
    bal_a = co.balanced_mae(f["abs_e_api"], f["bin_api"]).balanced_mae
    return bal_l - bal_a


_merged_verify = _verify_pi.reset_index().merge(
    _verify_pi_api.reset_index(), on="image", suffixes=("_local", "_api"),
)
_slow_diff = co.image_bootstrap(
    _merged_verify, _slow_diff_stat, _rng_c, image_col="image", bin_col="bin_local", B=2_000,
)
_fast_diff = fast_paired_diff_bootstrap(_verify_pi, _verify_pi_api, "balanced_mae", _rng_d, B=2_000)
assert np.isclose(_slow_diff.estimate, _fast_diff.estimate, atol=1e-9), (
    "fast-path paired-difference point estimate diverged from the shared implementation"
)
assert np.isclose(_slow_diff.ci_lo, _fast_diff.ci_lo, atol=1e-6) and np.isclose(_slow_diff.ci_hi, _fast_diff.ci_hi, atol=1e-6), (
    "fast-path paired-difference interval diverged from the shared implementation under an identical draw sequence"
)
print(f"Fast-path paired-difference verification passed: local-minus-API balanced MAE = "
      f"{_fast_diff.estimate:.4f} [{_fast_diff.ci_lo:.4f}, {_fast_diff.ci_hi:.4f}] on both "
      f"implementations (B=2,000 check run).")

# %% [markdown]
# ### Per-configuration table (24 rows) — descriptive, intervals, no correction
#
# Both metrics on both paths, the paired local-minus-API difference on each
# with a BCa interval, the rank on each path by balanced MAE, and the rank
# change. No p-value anywhere in this table: with 24 configurations and no
# pre-specified pairing between them, a p-value here would need its own
# multiple-comparison correction that this table does not attempt, so the
# comparison stays a magnitude with an interval.

# %%
combo_rows = []
for (model, prompt), loc in local_by_combo.items():
    api = api_by_combo[(model, prompt)]

    mae_o_ci = fast_image_bootstrap(loc["per_image"], "overall_mae", rng_level_ci)
    mae_b_ci = fast_image_bootstrap(loc["per_image"], "balanced_mae", rng_level_ci)
    mae_o_ci_api = fast_image_bootstrap(api["per_image"], "overall_mae", rng_level_ci)
    mae_b_ci_api = fast_image_bootstrap(api["per_image"], "balanced_mae", rng_level_ci)

    diff_o = fast_paired_diff_bootstrap(loc["per_image"], api["per_image"], "overall_mae", rng_diff_ci)
    diff_b = fast_paired_diff_bootstrap(loc["per_image"], api["per_image"], "balanced_mae", rng_diff_ci)

    # Llama-4-Maverick's run-to-run reproducibility floor is measured on the
    # overall-MAE scale (the 100-image determinism subsample has too few
    # high-cover images to support a bin-weighted floor). Any directional
    # claim about Maverick's balanced MAE therefore carries a flag saying so,
    # rather than a floor comparison this data cannot support.
    if model == "Llama-4-Maverick":
        floor_branch = co.maverick_balanced_mae_claim_branch(maverick_floor.delta_mav)
    else:
        floor_branch = {"floor_not_estimable_for_balanced_mae": False, "maverick_floor_delta": np.nan, "caveat": ""}

    combo_rows.append({
        "question_id": "Q7", "model": model, "prompt": prompt,
        "overall_mae_local": loc["overall_mae"], "overall_mae_local_ci_lo": mae_o_ci.ci_lo,
        "overall_mae_local_ci_hi": mae_o_ci.ci_hi,
        "overall_mae_api": api["overall_mae"], "overall_mae_api_ci_lo": mae_o_ci_api.ci_lo,
        "overall_mae_api_ci_hi": mae_o_ci_api.ci_hi,
        "overall_mae_diff_local_minus_api": diff_o.estimate,
        "overall_mae_diff_ci_lo": diff_o.ci_lo, "overall_mae_diff_ci_hi": diff_o.ci_hi,
        "overall_mae_diff_ci_method": diff_o.ci_method,
        "balanced_mae_local": loc["balanced_mae"], "balanced_mae_local_ci_lo": mae_b_ci.ci_lo,
        "balanced_mae_local_ci_hi": mae_b_ci.ci_hi,
        "balanced_mae_api": api["balanced_mae"], "balanced_mae_api_ci_lo": mae_b_ci_api.ci_lo,
        "balanced_mae_api_ci_hi": mae_b_ci_api.ci_hi,
        "balanced_mae_diff_local_minus_api": diff_b.estimate,
        "balanced_mae_diff_ci_lo": diff_b.ci_lo, "balanced_mae_diff_ci_hi": diff_b.ci_hi,
        "balanced_mae_diff_ci_method": diff_b.ci_method,
        "balanced_mae_interval_uncorrected": True,
        "floor_not_estimable_for_balanced_mae": floor_branch["floor_not_estimable_for_balanced_mae"],
        "maverick_floor_delta": floor_branch["maverick_floor_delta"],
        "caveat": floor_branch["caveat"],
        "tier": "secondary", "corrected": False, "claim_wording": "stack and possibly weights",
    })

pathway_by_configuration = pd.DataFrame(combo_rows)

# Rank on each path by balanced MAE (lower = better = rank 1), and the change.
pathway_by_configuration["rank_local"] = pathway_by_configuration["balanced_mae_local"].rank(method="min").astype(int)
pathway_by_configuration["rank_api"] = pathway_by_configuration["balanced_mae_api"].rank(method="min").astype(int)
pathway_by_configuration["rank_change_local_minus_api"] = (
    pathway_by_configuration["rank_local"] - pathway_by_configuration["rank_api"]
)
pathway_by_configuration = pathway_by_configuration.sort_values("balanced_mae_local").reset_index(drop=True)

print(f"Per-configuration table: {len(pathway_by_configuration)} rows (expected 24)")
pathway_by_configuration[[
    "model", "prompt", "overall_mae_local", "overall_mae_api", "balanced_mae_local",
    "balanced_mae_api", "rank_local", "rank_api", "rank_change_local_minus_api",
]]

# %% [markdown]
# **The best configuration is not the same on the two paths.** Locally it is
# Llama-4-Maverick under *Short*; through the API it is Qwen-2.5 under
# *Grid-Overlay*.

# %%
best_local_row = pathway_by_configuration.loc[pathway_by_configuration["rank_local"] == 1].iloc[0]
best_api_row = pathway_by_configuration.loc[pathway_by_configuration["rank_api"] == 1].iloc[0]
print(f"Best locally: {best_local_row['model']} x {best_local_row['prompt']} "
      f"at balanced MAE {best_local_row['balanced_mae_local']:.3f}")
print(f"Best through the API: {best_api_row['model']} x {best_api_row['prompt']} "
      f"at balanced MAE {best_api_row['balanced_mae_api']:.3f}")

assert_reproduces("best_local_balanced_mae", best_local_row["balanced_mae_local"], 11.209, atol=0.01)
assert_reproduces("best_api_balanced_mae", best_api_row["balanced_mae_api"], 11.620, atol=0.01)
assert best_local_row["model"] == "Llama-4-Maverick" and best_local_row["prompt"] == "Short", (
    "best-local configuration moved away from Llama-4-Maverick x Short"
)
assert best_api_row["model"] == "Qwen-2.5" and best_api_row["prompt"] == "Grid-Overlay", (
    "best-API configuration moved away from Qwen-2.5 x Grid-Overlay"
)
print("Best-configuration identities and balanced-MAE values match the published figures.")

# Where the local winner falls under the API path.
maverick_short_api_rank = pathway_by_configuration.loc[
    (pathway_by_configuration["model"] == "Llama-4-Maverick") & (pathway_by_configuration["prompt"] == "Short"),
    "rank_api",
].iloc[0]
maverick_short_rise = pathway_by_configuration.loc[
    (pathway_by_configuration["model"] == "Llama-4-Maverick") & (pathway_by_configuration["prompt"] == "Short"),
    "balanced_mae_diff_local_minus_api",
].iloc[0]
maverick_short_rise_ci = pathway_by_configuration.loc[
    (pathway_by_configuration["model"] == "Llama-4-Maverick") & (pathway_by_configuration["prompt"] == "Short"),
    ["balanced_mae_diff_ci_lo", "balanced_mae_diff_ci_hi"],
].iloc[0]
print(f"Llama-4-Maverick x Short falls to rank {maverick_short_api_rank} through the API, "
      f"its balanced MAE rising by {-maverick_short_rise:.3f} "
      f"[{-maverick_short_rise_ci['balanced_mae_diff_ci_hi']:.3f}, {-maverick_short_rise_ci['balanced_mae_diff_ci_lo']:.3f}]")

# %% [markdown]
# ### Per-model table (6 rows) — the Holm-corrected Wilcoxon
#
# The same metrics, pooled over the four prompts, plus the one test in this
# notebook: a paired two-sided Wilcoxon signed-rank on per-image absolute
# error, local minus API, corrected with Holm-Bonferroni across the six
# models. Companion effect sizes (Hodges-Lehmann median difference,
# matched-pairs rank-biserial correlation, win rate) travel with every row.
# The Llama-4-Maverick row additionally carries the reproducibility floor on
# the overall-MAE scale -- exactly the scale the Wilcoxon runs on and exactly
# the scale the floor was measured on.

# %%
model_rows = []
raw_p = []
per_model_results = {}

for model in co.MODELS:
    loc = local_by_model[(model,)]
    api = api_by_model[(model,)]

    merged = loc["per_image"].reset_index().merge(
        api["per_image"].reset_index(), on="image", suffixes=("_local", "_api"),
    )
    assert len(merged) == 1155, f"{model}: expected 1,155 paired images, got {len(merged)}"

    x = merged["abs_e_local"].values  # local |e|, per image
    y = merged["abs_e_api"].values    # API |e|, per image
    diff = x - y                      # positive => local had the larger |e| (API more accurate)

    wil = co.paired_wilcoxon(x, y)
    hl = co.hodges_lehmann(diff)
    rb = co.rank_biserial_matched_pairs(diff)
    wr = co.win_rate(x, y)  # "win" = local has the smaller |e|

    mae_o_ci = fast_image_bootstrap(loc["per_image"], "overall_mae", rng_level_ci)
    mae_b_ci = fast_image_bootstrap(loc["per_image"], "balanced_mae", rng_level_ci)
    mae_o_ci_api = fast_image_bootstrap(api["per_image"], "overall_mae", rng_level_ci)
    mae_b_ci_api = fast_image_bootstrap(api["per_image"], "balanced_mae", rng_level_ci)

    diff_o = fast_paired_diff_bootstrap(loc["per_image"], api["per_image"], "overall_mae", rng_diff_ci)
    diff_b = fast_paired_diff_bootstrap(loc["per_image"], api["per_image"], "balanced_mae", rng_diff_ci)

    is_maverick = model == "Llama-4-Maverick"
    within_floor = co.maverick_within_floor(diff_o.estimate, maverick_floor.delta_mav) if is_maverick else None

    # Llama-4-Maverick's balanced-MAE difference has no equivalent floor to
    # be read against -- the floor is only ever measured on the overall-MAE
    # scale -- so its balanced-MAE row is flagged rather than given a
    # within/above-floor verdict it cannot support.
    if is_maverick:
        floor_branch = co.maverick_balanced_mae_claim_branch(maverick_floor.delta_mav)
    else:
        floor_branch = {"floor_not_estimable_for_balanced_mae": False, "caveat": ""}

    row = {
        "question_id": "Q7", "model": model, "n": int(len(merged)),
        "overall_mae_local": loc["overall_mae"], "overall_mae_local_ci_lo": mae_o_ci.ci_lo,
        "overall_mae_local_ci_hi": mae_o_ci.ci_hi,
        "overall_mae_api": api["overall_mae"], "overall_mae_api_ci_lo": mae_o_ci_api.ci_lo,
        "overall_mae_api_ci_hi": mae_o_ci_api.ci_hi,
        "overall_mae_diff_local_minus_api": diff_o.estimate,
        "overall_mae_diff_ci_lo": diff_o.ci_lo, "overall_mae_diff_ci_hi": diff_o.ci_hi,
        "overall_mae_diff_ci_method": diff_o.ci_method,
        "balanced_mae_local": loc["balanced_mae"], "balanced_mae_local_ci_lo": mae_b_ci.ci_lo,
        "balanced_mae_local_ci_hi": mae_b_ci.ci_hi,
        "balanced_mae_api": api["balanced_mae"], "balanced_mae_api_ci_lo": mae_b_ci_api.ci_lo,
        "balanced_mae_api_ci_hi": mae_b_ci_api.ci_hi,
        "balanced_mae_diff_local_minus_api": diff_b.estimate,
        "balanced_mae_diff_ci_lo": diff_b.ci_lo, "balanced_mae_diff_ci_hi": diff_b.ci_hi,
        "balanced_mae_diff_ci_method": diff_b.ci_method,
        "balanced_mae_interval_uncorrected": True,
        "wilcoxon_statistic": wil.statistic, "p_raw": wil.p_value, "p_holm": np.nan,
        "n_zero_diff": wil.n_zero_diff, "n_tied_ranks": wil.n_tied_ranks,
        "hl_median_diff_local_minus_api": hl, "rank_biserial": rb,
        "win_rate_local": wr["win_rate_a"], "win_rate_api": wr["win_rate_b"], "tie_rate": wr["tie_rate"],
        "c1_serving_confounded": False,
        "c1_note": "both sides are the same model; the comparison crosses stack, not model family.",
        "maverick_floor_delta": maverick_floor.delta_mav if is_maverick else np.nan,
        "within_run_to_run_variability": within_floor,
        "floor_not_estimable_for_balanced_mae": floor_branch["floor_not_estimable_for_balanced_mae"],
        "caveat": floor_branch["caveat"],
        "tier": "secondary", "corrected": True, "claim_wording": "stack and possibly weights",
    }
    model_rows.append(row)
    raw_p.append(wil.p_value)
    per_model_results[model] = {"diff": diff, "x": x, "y": y}

p_holm = co.holm_adjust(raw_p, family="Q7", family_size=FAMILY_SIZE_Q7)
for i, row in enumerate(model_rows):
    row["p_holm"] = float(p_holm[i])

pathway_by_model = pd.DataFrame(model_rows).sort_values("model").reset_index(drop=True)
print(f"Per-model table: {len(pathway_by_model)} rows (expected 6)")
pathway_by_model[[
    "model", "overall_mae_local", "overall_mae_api", "balanced_mae_local", "balanced_mae_api",
    "p_raw", "p_holm", "within_run_to_run_variability",
]]

# %% [markdown]
# **The six per-model figures published with the paper.**
# `MAE_o` and `MAE_b` on each path, local then API, checked against the values
# printed in the paper. This cell fails if any of them moves, so the manuscript
# and the code cannot drift apart unnoticed.

# %%
_required = {
    "Qwen-2.5": {"mae_o_local": 6.641, "mae_o_api": 5.937, "mae_b_local": 12.883, "mae_b_api": 13.001},
    "Llama-4-Maverick": {"mae_o_local": 6.729, "mae_o_api": 6.819, "mae_b_local": 16.110, "mae_b_api": 15.835},
    "Gemma-3-12B": {"mae_o_local": 9.656, "mae_o_api": 9.341, "mae_b_local": 16.077, "mae_b_api": 17.299},
    "Gemma-3-27B": {"mae_o_local": 10.231, "mae_o_api": 10.375, "mae_b_local": 16.187, "mae_b_api": 17.925},
    "Llama-4-Scout": {"mae_o_local": 7.502, "mae_o_api": 10.211, "mae_b_local": 18.018, "mae_b_api": 18.347},
    "Mistral-Small-3.2": {"mae_o_local": 7.593, "mae_o_api": 6.296, "mae_b_local": 15.545, "mae_b_api": 20.210},
}

for _, r in pathway_by_model.iterrows():
    req = _required[r["model"]]
    assert_reproduces(f"overall_mae_local[{r['model']}]", r["overall_mae_local"], req["mae_o_local"])
    assert_reproduces(f"overall_mae_api[{r['model']}]", r["overall_mae_api"], req["mae_o_api"])
    assert_reproduces(f"balanced_mae_local[{r['model']}]", r["balanced_mae_local"], req["mae_b_local"])
    assert_reproduces(f"balanced_mae_api[{r['model']}]", r["balanced_mae_api"], req["mae_b_api"])
print("All six models' MAE_o and MAE_b, both paths, match the published values.")

# %% [markdown]
# **Reading the per-model rows.** Two models are unaffected in the sense that
# carries the most weight here -- Gemma-3-27B and Llama-4-Maverick are not
# separated by the Wilcoxon at any threshold. Two behave materially
# differently: Llama-4-Scout loses 2.7 points of `MAE_o` through the API, which
# is not the downward shift the other models mostly show and reads as a
# genuine degradation; Mistral-Small-3.2 loses 4.7 points of `MAE_b` while
# *gaining* 1.3 on `MAE_o`, which is the tension between the two metrics in
# its purest form on this frame. **Llama-4-Maverick's row carries the
# determinism floor**: its local-minus-API difference on the overall-MAE scale
# is read against δ_Mav before it is read as a stack effect at all.

# %%
mav_row = pathway_by_model.loc[pathway_by_model["model"] == "Llama-4-Maverick"].iloc[0]
print(f"Llama-4-Maverick: local-minus-API overall MAE difference = "
      f"{mav_row['overall_mae_diff_local_minus_api']:.4f}; delta_Mav = {maverick_floor.delta_mav:.4f}; "
      f"within_run_to_run_variability = {mav_row['within_run_to_run_variability']}")

# %% [markdown]
# ### Agreement quantities
#
# Exact-agreement rate, median absolute local-minus-API difference, empirical
# 2.5/97.5 percentile limits of agreement (not Bland-Altman's ±1.96 SD limits,
# because K5 above rejects normality of the stack difference for every model),
# tie-corrected Spearman, at both the per-model and per-model x prompt grain.

# %%
agreement_rows = []
for model in co.MODELS:
    loc = base_local[base_local["model"] == model]
    api = base_api[base_api["model"] == model]
    merged = loc.merge(api, on=["image", "prompt"], suffixes=("_local", "_api"), validate="one_to_one")
    assert len(merged) == 4620, f"{model}: expected 4,620 paired rows, got {len(merged)}"

    stack_diff = merged["vegetation_percent_local"] - merged["vegetation_percent_api"]
    exact_agree = float((stack_diff == 0).mean())
    abs_diff = stack_diff.abs()
    median_abs_diff = float(abs_diff.median())
    iqr_lo, iqr_hi = np.percentile(abs_diff, [25, 75])
    loa_lo, loa_hi = np.percentile(stack_diff, [2.5, 97.5])
    rho, rho_p = co.spearman_tie_corrected(
        merged["vegetation_percent_local"].values, merged["vegetation_percent_api"].values,
    )

    agreement_rows.append({
        "question_id": "Q7", "level": "model", "model": model, "prompt": "all (pooled)",
        "n_pairs": int(len(merged)), "exact_agreement_rate": exact_agree,
        "median_abs_diff_local_minus_api": median_abs_diff,
        "abs_diff_iqr_lo": float(iqr_lo), "abs_diff_iqr_hi": float(iqr_hi),
        "empirical_loa_2_5pct": float(loa_lo), "empirical_loa_97_5pct": float(loa_hi),
        "spearman_tie_corrected": rho, "spearman_p": rho_p,
        "tier": "secondary", "corrected": False, "claim_wording": "stack and possibly weights",
    })

for model in co.MODELS:
    for prompt in sorted(base_local["prompt"].unique()):
        loc = base_local[(base_local["model"] == model) & (base_local["prompt"] == prompt)]
        api = base_api[(base_api["model"] == model) & (base_api["prompt"] == prompt)]
        merged = loc.merge(api, on="image", suffixes=("_local", "_api"), validate="one_to_one")
        assert len(merged) == 1155, f"{model}/{prompt}: expected 1,155 paired rows, got {len(merged)}"

        stack_diff = merged["vegetation_percent_local"] - merged["vegetation_percent_api"]
        exact_agree = float((stack_diff == 0).mean())
        abs_diff = stack_diff.abs()
        median_abs_diff = float(abs_diff.median())
        iqr_lo, iqr_hi = np.percentile(abs_diff, [25, 75])
        loa_lo, loa_hi = np.percentile(stack_diff, [2.5, 97.5])
        rho, rho_p = co.spearman_tie_corrected(
            merged["vegetation_percent_local"].values, merged["vegetation_percent_api"].values,
        )

        agreement_rows.append({
            "question_id": "Q7", "level": "model_x_prompt", "model": model, "prompt": prompt,
            "n_pairs": int(len(merged)), "exact_agreement_rate": exact_agree,
            "median_abs_diff_local_minus_api": median_abs_diff,
            "abs_diff_iqr_lo": float(iqr_lo), "abs_diff_iqr_hi": float(iqr_hi),
            "empirical_loa_2_5pct": float(loa_lo), "empirical_loa_97_5pct": float(loa_hi),
            "spearman_tie_corrected": rho, "spearman_p": rho_p,
            "tier": "secondary", "corrected": False, "claim_wording": "stack and possibly weights",
        })

pathway_agreement = pd.DataFrame(agreement_rows)

overall_stack_diff = (base_local.merge(
    base_api, on=["image", "prompt", "model"], suffixes=("_local", "_api"),
))
overall_stack_diff["stack_diff"] = (
    overall_stack_diff["vegetation_percent_local"] - overall_stack_diff["vegetation_percent_api"]
)
overall_exact_agree = float((overall_stack_diff["stack_diff"] == 0).mean())
overall_median_abs_diff = float(overall_stack_diff["stack_diff"].abs().median())

print(f"Exact agreement across all 27,720 matched responses: {overall_exact_agree:.4f} "
      f"({overall_exact_agree * 100:.1f}%)")
print(f"Median |local - api| across all matched responses: {overall_median_abs_diff:.4f} cover points")

assert_reproduces("exact_agreement_rate", overall_exact_agree, 0.496, atol=0.002)
assert_reproduces("median_abs_diff", overall_median_abs_diff, 0.5, atol=0.05)
print("Exact-agreement rate and median absolute difference reproduce the required values: "
      "49.6% and 0.5 cover points.")

pathway_agreement[pathway_agreement["level"] == "model"][
    ["model", "n_pairs", "exact_agreement_rate", "median_abs_diff_local_minus_api",
     "empirical_loa_2_5pct", "empirical_loa_97_5pct", "spearman_tie_corrected"]
]

# %% [markdown]
# ### Kendall tau-b on the 24-configuration balanced-MAE ranking
#
# The practically important form of the agreement question: does the ranking
# by balanced MAE over the 24 model x prompt configurations agree between the
# two paths? No p-value is reported for this rank correlation -- the 24 units
# are not independent exchangeable pairs, they are built from the same 1,155
# images and share models, prompts and reference, so `stats.kendalltau`'s
# asymptotic null does not apply here, exactly as Q1's own respecified
# ranking-agreement construction states.

# %%
tau_combo, tau_combo_p = stats.kendalltau(
    pathway_by_configuration["balanced_mae_local"], pathway_by_configuration["balanced_mae_api"],
)
tau_combo = float(tau_combo)
pct_concordant = (tau_combo + 1) / 2  # tau_b -> share of concordant pairs, ignoring ties
print(f"Kendall tau_b (24-configuration balanced-MAE ranking, local vs API) = {tau_combo:.4f}")
print(f"-> {pct_concordant * 100:.1f}% of configuration pairs ordered alike")

assert_reproduces("kendall_tau_b", tau_combo, 0.746, atol=0.005)
assert_reproduces("pct_concordant", pct_concordant * 100, 87.3, atol=0.2)
print("Kendall tau_b and the derived concordant-pair share reproduce the required values: "
      "0.746 and 87.3%.")

# %% [markdown]
# ## Rank reversals — the rule for what counts
#
# **A reversal counts only if the two configurations were separated on the
# local path.** Two configurations that were never distinguishable did not
# have an order to reverse, so swapping them under the API path is not a
# finding. Operationally: for every pair of configurations whose relative
# order by balanced MAE flips between the two paths, the local-path balanced-
# MAE difference is bootstrapped, and the reversal counts only if that
# interval excludes zero. This is data-driven and needs no chosen threshold,
# which is the reason for preferring it over an arbitrary minimum-gap rule.
#
# **The interval is BCa, exactly as it is everywhere else in this study**
# — never the plain percentile interval, which is not the method
# this plan uses and reads as narrower or wider than BCa on skewed resample
# distributions. `fast_paired_diff_bootstrap` computes both internally and
# reports whichever the shared library's own fallback rule selects: BCa where
# it is defined, the percentile interval only where BCa's bias-correction or
# acceleration is undefined (fewer than 50 distinct bootstrap values, or the
# observed statistic sits exactly at the resample distribution's edge). Which
# method was used for each pair is recorded in `local_gap_ci_method` in
# `Q7_rank_reversals.csv`, so a silent mix of the two is never left invisible.

# %%
combo_keys = list(zip(pathway_by_configuration["model"], pathway_by_configuration["prompt"]))
n_combo = len(combo_keys)
bal_local = dict(zip(combo_keys, pathway_by_configuration["balanced_mae_local"]))
bal_api = dict(zip(combo_keys, pathway_by_configuration["balanced_mae_api"]))

per_image_by_combo = {(m, p): local_by_combo[(m, p)]["per_image"] for (m, p) in combo_keys}

pair_rows = []
n_pairs_total = 0
n_reversed = 0
for i in range(n_combo):
    for j in range(i + 1, n_combo):
        n_pairs_total += 1
        key_a, key_b = combo_keys[i], combo_keys[j]
        order_local = np.sign(bal_local[key_a] - bal_local[key_b])
        order_api = np.sign(bal_api[key_a] - bal_api[key_b])
        if order_local == 0 or order_api == 0:
            reversed_pair = False
        else:
            reversed_pair = order_local != order_api
        if reversed_pair:
            n_reversed += 1
            pi_a = per_image_by_combo[key_a]
            pi_b = per_image_by_combo[key_b]
            boot = fast_paired_diff_bootstrap(pi_a, pi_b, "balanced_mae", rng_reversal)
            separated_locally = bool(boot.ci_lo > 0 or boot.ci_hi < 0)
            pair_rows.append({
                "question_id": "Q7",
                "config_a_model": key_a[0], "config_a_prompt": key_a[1],
                "config_b_model": key_b[0], "config_b_prompt": key_b[1],
                "balanced_mae_local_a": bal_local[key_a], "balanced_mae_local_b": bal_local[key_b],
                "balanced_mae_api_a": bal_api[key_a], "balanced_mae_api_b": bal_api[key_b],
                "local_gap_a_minus_b": boot.estimate,
                "local_gap_ci_lo": boot.ci_lo, "local_gap_ci_hi": boot.ci_hi,
                "local_gap_ci_method": boot.ci_method,
                "separated_locally": separated_locally,
                "counts_as_real_reversal": separated_locally,
                "tier": "secondary", "corrected": False, "claim_wording": "stack and possibly weights",
            })

rank_reversals = pd.DataFrame(pair_rows)
n_real_reversals = int(rank_reversals["counts_as_real_reversal"].sum()) if len(rank_reversals) else 0
n_not_separated = len(rank_reversals) - n_real_reversals

print(f"Total configuration pairs: {n_pairs_total} (expected 276)")
print(f"Reversed pairs: {n_reversed} (expected 35)")
print(f"Real reversals (separated locally): {n_real_reversals} (expected 12); "
      f"not separated: {n_not_separated} (expected 23)")
print("CI method used per reversed pair:")
print(rank_reversals["local_gap_ci_method"].value_counts().to_string())

assert n_pairs_total == 276, f"expected 276 configuration pairs, got {n_pairs_total}"
assert n_reversed == 35, f"expected 35 reversed pairs, got {n_reversed}"
assert n_real_reversals == 12, f"expected 12 real reversals, got {n_real_reversals}"
assert n_not_separated == 23, f"expected 23 pairs that do not count, got {n_not_separated}"
print("Pair counts reproduce the required values: 276 pairs, 35 reversed, "
      "12 separated locally (real reversals), 23 not separated.")

# %%
rank_reversals.sort_values("counts_as_real_reversal", ascending=False).head(15)

# %% [markdown]
# **A large share of the real reversals involve one configuration.**
# Llama-4-Maverick under *Detailed* improves substantially on the API path,
# and Mistral-Small-3.2 under *Detailed* worsens by a comparable amount --
# between them these two configurations generate much of the instability in
# the top of the ranking. The counts below are read from the corrected set of
# 12 real reversals, not asserted against a fixed figure, since which
# configurations concentrate the instability is a description of the result
# rather than a value this notebook is required to reproduce.

# %%
real_reversals = rank_reversals[rank_reversals["counts_as_real_reversal"]]

detailed_mav = real_reversals[
    ((real_reversals["config_a_model"] == "Llama-4-Maverick") & (real_reversals["config_a_prompt"] == "Detailed"))
    | ((real_reversals["config_b_model"] == "Llama-4-Maverick") & (real_reversals["config_b_prompt"] == "Detailed"))
]
detailed_mistral = real_reversals[
    ((real_reversals["config_a_model"] == "Mistral-Small-3.2") & (real_reversals["config_a_prompt"] == "Detailed"))
    | ((real_reversals["config_b_model"] == "Mistral-Small-3.2") & (real_reversals["config_b_prompt"] == "Detailed"))
]
print(f"Real reversals involving Llama-4-Maverick x Detailed: {len(detailed_mav)} of {len(real_reversals)}")
print(f"Real reversals involving Mistral-Small-3.2 x Detailed: {len(detailed_mistral)} of {len(real_reversals)}")

# %% [markdown]
# ## Chart
#
# Two panels. **Left:** per-configuration balanced MAE, local against API, one
# point per model x prompt configuration, coloured by whether that
# configuration is on one side of a real (locally-separated) reversal. Points
# on the diagonal agree between paths; points off it are where the ranking
# moves. **Right:** the six per-model `MAE_o` local-minus-API differences with
# their Holm-adjusted significance, so the two models the Wilcoxon separates
# from zero are visible directly rather than only as p-values in a table.

# %%
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

ax = axes[0]
reversal_combo_keys = set()
for _, r in rank_reversals[rank_reversals["counts_as_real_reversal"]].iterrows():
    reversal_combo_keys.add((r["config_a_model"], r["config_a_prompt"]))
    reversal_combo_keys.add((r["config_b_model"], r["config_b_prompt"]))

colors = [
    "firebrick" if (m, p) in reversal_combo_keys else "steelblue"
    for m, p in zip(pathway_by_configuration["model"], pathway_by_configuration["prompt"])
]
ax.scatter(
    pathway_by_configuration["balanced_mae_local"], pathway_by_configuration["balanced_mae_api"],
    c=colors, s=40, zorder=3,
)
lims = [
    min(pathway_by_configuration["balanced_mae_local"].min(), pathway_by_configuration["balanced_mae_api"].min()) - 1,
    max(pathway_by_configuration["balanced_mae_local"].max(), pathway_by_configuration["balanced_mae_api"].max()) + 1,
]
ax.plot(lims, lims, color="gray", linewidth=0.8, linestyle="--", zorder=1)
ax.set_xlim(lims)
ax.set_ylim(lims)
ax.set_xlabel("balanced MAE, local path (cover points)")
ax.set_ylabel("balanced MAE, API path (cover points)")
ax.set_title(f"24 configurations, balanced MAE by path\n"
             f"red = involved in a reversal separated on the local path ({n_real_reversals} pairs)")

ax = axes[1]
plot_df = pathway_by_model.sort_values("overall_mae_diff_local_minus_api")
colors_bar = ["firebrick" if p < holm_threshold_q7 else "lightgray" for p in plot_df["p_holm"]]
y_pos = np.arange(len(plot_df))
ax.barh(y_pos, plot_df["overall_mae_diff_local_minus_api"], color=colors_bar)
ax.set_yticks(y_pos)
ax.set_yticklabels(plot_df["model"], fontsize=9)
ax.axvline(0, color="black", linewidth=0.8)
ax.set_xlabel("MAE_o, local minus API (cover points)")
ax.set_title("Per-model overall-MAE difference\nred = Holm-significant within Q7's own family of 6 (alpha=0.00833)")

fig.suptitle("Q7 -- local vs API serving stack (base variant only; secondary, appendix at most)", y=1.02)
fig.tight_layout()
fig.savefig(RENDERED_DIR / "Q7_pathway_comparison.png", dpi=110, bbox_inches="tight")
plt.show()

# %% [markdown]
# ## Assumption-check log

# %%
k3_by_model = k3_df.copy()
k3_by_model["id"] = "K3"
k3_by_model["description"] = "tie burden of the per-image local-minus-API absolute-error difference; reported, never used to switch test"
k3_by_model["passed"] = ~k3_by_model["tie_burden_exceeded"]
k3_by_model["detail"] = k3_by_model.apply(
    lambda r: f"model={r['model']}, n_zero={r['n_zero']}, n={r['n']}, zero_share={r['zero_share']:.4f}",
    axis=1,
)

k5_by_model = k5_df.copy()
k5_by_model["id"] = "K5"
k5_by_model["description"] = "D'Agostino-Pearson normality of pooled stack difference, context only"
k5_by_model["passed"] = ~k5_by_model["normality_rejected"]
k5_by_model["detail"] = k5_by_model.apply(
    lambda r: f"model={r['model']}, statistic={r['statistic']:.4f}, p={r['p_value']:.4g}",
    axis=1,
)

assumption_checks_df = pd.concat(
    [
        checks_df[["id", "description", "passed", "detail"]],
        pd.DataFrame([vars(k1_result), vars(c11_result)])[["id", "description", "passed", "detail"]],
        k3_by_model[["id", "description", "passed", "detail"]],
        k5_by_model[["id", "description", "passed", "detail"]],
    ],
    ignore_index=True,
)
assumption_checks_df.insert(0, "question_id", "Q7")

assumption_checks_df["passed"] = assumption_checks_df["passed"].astype(bool)
print(f"{int(assumption_checks_df['passed'].sum())} of {len(assumption_checks_df)} checks passed "
      f"(K5 rows are reported for context only and never gate anything).")
assumption_checks_df.tail(12)

# %% [markdown]
# ## Result
#
# **Agreement.** The two pathways agree exactly on 49.6% of 27,720 matched
# responses, and the typical disagreement is small -- a median absolute
# difference of 0.5 cover points (`Q7_pathway_agreement.csv`). The empirical
# 2.5/97.5 percentile limits of agreement are reported rather than
# Bland-Altman's ±1.96 SD limits because K5 rejects normality of the stack
# difference for every model.
#
# **Accuracy, on both metrics, both paths, both grains.** `Q7_pathway_by_
# configuration.csv` (24 rows, descriptive, uncorrected) and `Q7_pathway_by_
# model.csv` (6 rows, carrying the Holm-corrected Wilcoxon) report `MAE_o` and
# `MAE_b` on each path with intervals, the paired local-minus-API difference
# with its own interval, and -- at the model grain -- the one test in this
# notebook. Two models, Gemma-3-27B and Llama-4-Maverick, are not separated by
# the Wilcoxon at Q7's own Holm threshold (0.00833). Two behave materially
# differently: Llama-4-Scout's `MAE_o` degrades by 2.7 points through the API,
# and Mistral-Small-3.2 trades a 1.3-point `MAE_o` gain for a 4.7-point `MAE_b`
# loss. **`MAE_o` improves through the API for three of the six models** --
# Qwen-2.5, Gemma-3-12B and Mistral-Small-3.2 -- which is the fact that keeps
# this notebook from being read as an accuracy comparison with a predetermined
# winner.
#
# **Ranking agreement.** Kendall tau_b on the 24-configuration balanced-MAE
# ranking is 0.746: the two paths order 87.3% of configuration pairs alike.
# Of 276 pairs, 35 reverse order between the two paths, but **only 12 of those
# were ever separated on the local path** (`Q7_rank_reversals.csv`) -- the
# other 23 pairs were statistically indistinguishable locally, so swapping
# their order is not a finding under the rule this notebook applies. Five of
# the 12 real reversals trace to two configurations under the *Detailed*
# prompt: three involve Llama-4-Maverick, which improves sharply through the
# API, and two involve Mistral-Small-3.2, which worsens by a comparable
# amount.
#
# **The instability reaches the top of the ranking.** The best configuration
# locally is Llama-4-Maverick under *Short*; through the API it is Qwen-2.5
# under *Grid-Overlay*, and Maverick under *Short* falls out of the top ten.
# That reversal is one of the 12 real ones -- a leaderboard built from one
# serving path does not transfer to the other at the top.
#
# **What this notebook does and does not establish.** None of the numbers
# above license a claim that either serving path is more accurate: `MAE_o`
# improves through the API for half the models, and every comparison here
# crosses stack **and possibly weights**, a confound this design cannot
# resolve (C10). What the numbers do establish is narrower and, for a
# reader deciding how to build on this work, more useful: **the local pathway
# is the one this study reports because it is the one that can be checked.**
# Its specification -- framework, precision, hardware, decoding parameters --
# is recorded, and re-running it reproduced 100 of 100 responses exactly for
# five of six models and 92 of 100 for Llama-4-Maverick, with every
# disagreement exactly 10 cover points, bounding Maverick's own run-to-run
# contribution to overall MAE at 0.65 [0.25, 1.15] cover points
# (`Q1_determinism_floor.csv`) -- smaller than every per-model `MAE_o`
# difference reported here except Qwen-2.5's and Llama-4-Scout's. An API
# number carries no equivalent guarantee, because the system that produced it
# is not specified and may not be the same system tomorrow. **None of this
# analysis enters the paper body; it is an appendix at most**, and every
# sentence built from it reads "stack and possibly weights", never "stack"
# alone.

# %% [markdown]
# ## Ranking agreement across the two pathways
#
# How far the two serving paths agree on the *order* of configurations, rather
# than on their absolute error. Reported at three levels: the six models, the
# four prompts, and the 24 model-by-prompt configurations. Kendall's tau-b is
# given as a point estimate with no p-value, because the units are not
# independent exchangeable pairs: they come from the same 1,155 photographs and
# share models, prompts and reference values, so the asymptotic null does not
# apply. Section 3.7.3 quotes the 24-configuration value.

# %%
local_by_prompt = level_metrics(base_local, ["prompt"])
api_by_prompt = level_metrics(base_api, ["prompt"])


def _ranked(metrics: dict) -> pd.DataFrame:
    """Level metrics as a frame ordered best-first on balanced MAE."""
    rows = [{"key": k, "balanced_mae": v["balanced_mae"]} for k, v in metrics.items()]
    return pd.DataFrame(rows).sort_values("balanced_mae").reset_index(drop=True)


def _tau_b(local_metrics: dict, api_metrics: dict) -> float:
    """Kendall tau-b over the keys the two pathways share."""
    loc, api = _ranked(local_metrics), _ranked(api_metrics)
    merged = loc.merge(api, on="key", suffixes=("_local", "_api"))
    tau, _p_not_reported = stats.kendalltau(
        merged["balanced_mae_local"], merged["balanced_mae_api"]
    )
    return float(tau)


def _winner(metrics: dict) -> tuple:
    return _ranked(metrics).iloc[0]["key"]


tau_model_level = _tau_b(local_by_model, api_by_model)
tau_prompt_level = _tau_b(local_by_prompt, api_by_prompt)
tau_combo_level = _tau_b(local_by_combo, api_by_combo)

# the configuration-level tau_b is also computed above; the two must agree
assert abs(tau_combo_level - tau_combo) < 1e-12, (
    f"ranking-agreement tau_b {tau_combo_level} disagrees with the value "
    f"computed earlier in this notebook, {tau_combo}"
)

w_model_local, w_model_api = _winner(local_by_model), _winner(api_by_model)
w_prompt_local, w_prompt_api = _winner(local_by_prompt), _winner(api_by_prompt)
w_combo_local, w_combo_api = _winner(local_by_combo), _winner(api_by_combo)

ranking_agreement = pd.DataFrame([
    {
        "question_id": "Q7", "ranking_level": "model", "n_units": len(local_by_model),
        "kendall_tau_b": tau_model_level,
        "top_local": w_model_local[0], "top_api": w_model_api[0],
        "top_configuration_matches": w_model_local == w_model_api,
        "tier": "secondary", "corrected": False,
        "claim_wording": "stack and possibly weights",
    },
    {
        "question_id": "Q7", "ranking_level": "prompt", "n_units": len(local_by_prompt),
        "kendall_tau_b": tau_prompt_level,
        "top_local": w_prompt_local[0], "top_api": w_prompt_api[0],
        "top_configuration_matches": w_prompt_local == w_prompt_api,
        "tier": "secondary", "corrected": False,
        "claim_wording": "stack and possibly weights",
    },
    {
        "question_id": "Q7", "ranking_level": "model_x_prompt", "n_units": len(local_by_combo),
        "kendall_tau_b": tau_combo_level,
        "top_local": f"{w_combo_local[0]} / {w_combo_local[1]}",
        "top_api": f"{w_combo_api[0]} / {w_combo_api[1]}",
        "top_configuration_matches": w_combo_local == w_combo_api,
        "tier": "secondary", "corrected": False,
        "claim_wording": "stack and possibly weights",
    },
])
print(ranking_agreement.to_string(index=False))

# %%
pathway_out = RESULTS_DIR / "Q7_pathway_by_configuration.csv"
model_out = RESULTS_DIR / "Q7_pathway_by_model.csv"
agreement_out = RESULTS_DIR / "Q7_pathway_agreement.csv"
reversals_out = RESULTS_DIR / "Q7_rank_reversals.csv"
assumption_out = RESULTS_DIR / "Q7_assumption_checks.csv"
ranking_out = RESULTS_DIR / "Q7_ranking_agreement.csv"

pathway_by_configuration.to_csv(pathway_out, index=False)
pathway_by_model.to_csv(model_out, index=False)
pathway_agreement.to_csv(agreement_out, index=False)
rank_reversals.to_csv(reversals_out, index=False)
assumption_checks_df.to_csv(assumption_out, index=False)
ranking_agreement.to_csv(ranking_out, index=False)

print("\nWritten:")
for path, df in [
    (pathway_out, pathway_by_configuration), (model_out, pathway_by_model),
    (agreement_out, pathway_agreement), (reversals_out, rank_reversals),
    (assumption_out, assumption_checks_df),
]:
    print(f"  {path.relative_to(ROOT)}  ({len(df)} rows)")
